##  Plugin Information  ##
name: FlagGame
version: 0.1
main: syam.FlagGame.FlagGame
description: FlagMatch Gaming Plugin for SakuraServer
website: http://sakura-server.net/
depend: [Vault, WorldEdit]
softdepend: [DeathNotifier, dynmap]
##  Original Author     ##
author: syam
commands:
    flag:
      usage: /flag - to see the help
      aliases: [f, fg]
      description: To see the FlagGame help.
permissions:
    flag.user.join:
        default: op
        description: Allow join the game
    flag.admin.setup.check:
        default: op
        description: Allow check command
    flag.admin.setup.create:
        default: op
        description: Allow create command
    flag.admin.setup.delete:
        default: op
        description: Allow delete command
    flag.admin.setup.set:
        default: op
        description: Allow set command
    flag.admin.select:
        default: op
        description: Allow select command
    flag.admin.tp:
        default: op
        description: Allow tp command
    flag.admin.start:
        default: op
        description: Allow start command
    flag.admin.ready:
        default: op
        description: Allow ready command
    flag.admin.reload:
        default: op
        description: Allow reload command
    flag.admin.sign:
        default: op
        description: Allow place FlagGame sign
    flag.user.watch:
        default: op
        description: Allow watch command
    flag.user.info:
        default: op
        description: Allow info command
    flag.user.leave.spectate:
        default: op
        description: Allow leave from spectate area
    flag.user.leave.game:
        default: op
        description: Allow leave from game
    flag.user.leave.ready:
        default: op
        description: Allow leave from ready game
    flag.user.stats.self:
        default: op
        description: Allow show self stats
    flag.user.stats.other:
        default: op
        description: Allow show other player stats
    flag.admin.save:
        default: op
        description: Allow save map data
    flag.ignoreWorldProtect:
        default: op
        description: Allow Break/Place protected game-world
    flag.ignoreInteractEvent:
        default: op
        description: Allow Open/Close all doors/chests in game-world